### ISSUE TITLE
not clear how to use example.js

### ISSUE THREAD

**Issue by id347627** [johnelm/node-jxa#32]
what ide I should use to run and play around with example.js?
what do I need to set up?

**Comment by johnelm** [comment]
hi @id347627 

### what ide I should use to run and play around with example.js?

You can use any IDE you like to try the example.  My fave is vscode (Visual Studio Code).  As I mentioned in the README.

> So long as your editor can launch a shebang'd script, you can run or debug JXA while you edit.

I do this in vscode using the [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) extension.  Its `code-runner.respectShebang` config setting in vscode must be set to `true` (the default setting).

But, you don't have to use an IDE at all to run the script, and this is largely the 'raison d'être' for node-jxa..  to be able to run your JXA scripts, potentially using modules from NPM, from your terminal or from any script launcher that can start a shell script, e.g. FastScripts, Alfred, Automator, etc.

### what do I need to set up?
- install node-jxa globally, using `yarn` or `npm`, as described in the README file's [Installation and usage](https://github.com/johnelm/node-jxa#installation-and-usage) section.
- chmod the script so it has execute permissions: `chmod +x ./example.js`, also described in the README file's [Installation and usage](https://github.com/johnelm/node-jxa#installation-and-usage) section. (see comment at bottom)

#### Dependencies
You must also make sure the script's dependencies are installed and available to node-jxa, as mentioned in the [Project structure and availability of node modules](https://github.com/johnelm/node-jxa#project-structure-and-availability-of-node-modules) section of the README.

##### the `example.js` file
For the `example.js` file in a local clone of node-jxa, this is easiest by running `yarn` or `npm install` from your local clone's project dir.
  - please regard the comments in `example.js` for other requirements, i.e. permissions for showing OSX notifications

##### real-world usage
For real-world usage, you can install the dependencies:
  - globally via `npm install -g` or `yarn global add`, or
  - in any folder where node-jxa (actually Browserify) can find them, by running `npm install <module>` or `yarn add <module>`:
    - in the same dir as the script, creating `node_modules` as a sibling dir to your script, or
    - in any parent dir, creating `node_modules` as a '[great] uncle' dir to where your script is.

The logic for how node finds dependencies is detailed in the node.js docs [here](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders), in the few sections starting with 'Loading from `node_modules` Folders'.

**Comment by johnelm** [comment]
I just realized that the `example.js` script (in the git repo) doesn't have execute permissions; I've created an issue to update its permissions so it's not necessary to chmod it before trying it.

I'll make a note to add a bit more info on dependencies to the README too.
